apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: {{ cookiecutter.aws_iam_role }}
      groups:
        - {{ cookiecutter.rolebinding_name }}
  mapUsers: |
    - userarn: {{ cookiecutter.aws_iam_user }}
      groups:
        - {{ cookiecutter.rolebinding_name }}
