language: python
python:
  - "2.7"
  - "3.6"
  - "3.8"
  - "pypy3"
matrix:
  include:
    - python: 3.8
      dist: bionic
      sudo: true
install:
  - "pip install -r requirements.txt"
script:
  - pytest -v
